/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2018 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_DILITHIUMERR_H
# define HEADER_DILITHIUMERR_H

# ifdef  __cplusplus
extern "C"
# endif
int ERR_load_Dilithium_strings(void);

/*
 * Dilithium function codes.
 */
# define DILITHIUM_F_INT_DILITHIUM_VERIFY                             145
# define DILITHIUM_F_OLD_DILITHIUM_PRIV_DECODE                        147
# define DILITHIUM_F_PKEY_DILITHIUM_CTRL                              143
# define DILITHIUM_F_PKEY_DILITHIUM_CTRL_STR                          144
# define DILITHIUM_F_DILITHIUM_BUILTIN_KEYGEN                         129
# define DILITHIUM_F_DILITHIUM_CHECK_KEY                              123
# define DILITHIUM_F_DILITHIUM_CHECK_KEY_EX                           160
# define DILITHIUM_F_DILITHIUM_ITEM_VERIFY                            148
# define DILITHIUM_F_DILITHIUM_METH_DUP                               161
# define DILITHIUM_F_DILITHIUM_METH_NEW                               162
# define DILITHIUM_F_DILITHIUM_METH_SET1_NAME                         163
# define DILITHIUM_F_DILITHIUM_MULTIP_INFO_NEW                        166
# define DILITHIUM_F_DILITHIUM_NEW_METHOD                             106
# define DILITHIUM_F_DILITHIUM_NULL                                   124
# define DILITHIUM_F_DILITHIUM_NULL_PRIVATE_DECRYPT                   132
# define DILITHIUM_F_DILITHIUM_NULL_PRIVATE_ENCRYPT                   133
# define DILITHIUM_F_DILITHIUM_NULL_PUBLIC_DECRYPT                    134
# define DILITHIUM_F_DILITHIUM_NULL_PUBLIC_ENCRYPT                    135
# define DILITHIUM_F_DILITHIUM_PARAM_DECODE                           164
# define DILITHIUM_F_DILITHIUM_PRINT                                  115
# define DILITHIUM_F_DILITHIUM_PRINT_FP                               116
# define DILITHIUM_F_DILITHIUM_PRIV_DECODE                            150
# define DILITHIUM_F_DILITHIUM_KEY_COPYPRIV                           194
# define DILITHIUM_F_DILITHIUM_PRIV_ENCODE                            138
# define DILITHIUM_F_DILITHIUM_PUB_DECODE                             139
# define DILITHIUM_F_I2D_DILITHIUMPRIVATEKEY                          192
# define DILITHIUM_F_D2I_DILITHIUMPRIVATEKEY                          193
# define DILITHIUM_F_I2D_DILITHIUMPUBLICKEY                           195
# define DILITHIUM_F_D2I_DILITHIUMPUBLICKEY                           196
# define DILITHIUM_F_PKEY_DILITHIUM_SIGN                              197

/*
 * DILITHIUM reason codes.
 */
# define DILITHIUM_R_ALGORITHM_MISMATCH                         100
# define DILITHIUM_R_WRONG_KEY_SIZE                             101
# define DILITHIUM_R_BAD_FIXED_HEADER_DECRYPT                   102
# define DILITHIUM_R_BAD_MODE_VALUE                             103
# define DILITHIUM_R_BLOCK_TYPE_IS_NOT_01                       106
# define DILITHIUM_R_BLOCK_TYPE_IS_NOT_02                       107
# define DILITHIUM_R_DATA_TOO_LARGE                             109
# define DILITHIUM_R_DATA_TOO_LARGE_FOR_KEY_SIZE                110
# define DILITHIUM_R_DATA_TOO_SMALL                             111
# define DILITHIUM_R_DATA_TOO_SMALL_FOR_KEY_SIZE                122
# define DILITHIUM_R_FIRST_OCTET_INVALID                        133
# define DILITHIUM_R_INVALID_HEADER                             137
# define DILITHIUM_R_INVALID_LABEL                              160
# define DILITHIUM_R_INVALID_TRAILER                            139
# define DILITHIUM_R_KEY_SIZE_TOO_SMALL                         120
# define DILITHIUM_R_LAST_OCTET_INVALID                         134
# define DILITHIUM_R_NULL_BEFORE_BLOCK_MISSING                  113
# define DILITHIUM_R_SLEN_CHECK_FAILED                          136
# define DILITHIUM_R_SLEN_RECOVERY_FAILED                       135
# define DILITHIUM_R_UNKNOWN_ALGORITHM_TYPE                     117
# define DILITHIUM_R_UNSUPPORTED_ENCRYPTION_TYPE                162
# define DILITHIUM_R_UNSUPPORTED_LABEL_SOURCE                   163
# define DILITHIUM_R_VALUE_MISSING                              147
# define DILITHIUM_R_MISSING_PRIVATE_KEY                        148
# define DILITHIUM_R_MISSING_PUBLIC_KEY                         149
# define DILITHIUM_R_WRONG_SIGNATURE_LENGTH                     164
# define DILITHIUM_R_BUFFER_TOO_SMALL                           165

#endif
