/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2018 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#ifndef HEADER_KYBERERR_H
# define HEADER_KYBERERR_H

# ifdef  __cplusplus
extern "C"
# endif
int ERR_load_Kyber_strings(void);

/*
 * Kyber function codes.
 */
# define KYBER_F_INT_KYBER_VERIFY                             145
# define KYBER_F_OLD_KYBER_PRIV_DECODE                        147
# define KYBER_F_PKEY_KYBER_CTRL                              143
# define KYBER_F_PKEY_KYBER_CTRL_STR                          144
# define KYBER_F_KYBER_BUILTIN_KEYGEN                         129
# define KYBER_F_KYBER_CHECK_KEY                              123
# define KYBER_F_KYBER_CHECK_KEY_EX                           160
# define KYBER_F_KYBER_ITEM_VERIFY                            148
# define KYBER_F_KYBER_METH_DUP                               161
# define KYBER_F_KYBER_METH_NEW                               162
# define KYBER_F_KYBER_METH_SET1_NAME                         163
# define KYBER_F_KYBER_MULTIP_INFO_NEW                        166
# define KYBER_F_KYBER_NEW_METHOD                             106
# define KYBER_F_KYBER_NULL                                   124
# define KYBER_F_KYBER_NULL_PRIVATE_DECRYPT                   132
# define KYBER_F_KYBER_NULL_PRIVATE_ENCRYPT                   133
# define KYBER_F_KYBER_NULL_PUBLIC_DECRYPT                    134
# define KYBER_F_KYBER_NULL_PUBLIC_ENCRYPT                    135
# define KYBER_F_KYBER_PARAM_DECODE                           164
# define KYBER_F_KYBER_PRINT                                  115
# define KYBER_F_KYBER_PRINT_FP                               116
# define KYBER_F_KYBER_PRIV_DECODE                            150
# define KYBER_F_KYBER_KEY_COPYPRIV                           194
# define KYBER_F_KYBER_PRIV_ENCODE                            138
# define KYBER_F_KYBER_PUB_DECODE                             139
# define KYBER_F_I2D_KYBERPRIVATEKEY                          192
# define KYBER_F_D2I_KYBERPRIVATEKEY                          193
# define KYBER_F_I2D_KYBERPUBLICKEY                           195
# define KYBER_F_D2I_KYBERPUBLICKEY                           196

/*
 * KYBER reason codes.
 */
# define KYBER_R_ALGORITHM_MISMATCH                         100
# define KYBER_R_WRONG_KEY_SIZE                             101
# define KYBER_R_BAD_FIXED_HEADER_DECRYPT                   102
# define KYBER_R_BAD_MODE_VALUE                             103
# define KYBER_R_BLOCK_TYPE_IS_NOT_01                       106
# define KYBER_R_BLOCK_TYPE_IS_NOT_02                       107
# define KYBER_R_DATA_TOO_LARGE                             109
# define KYBER_R_DATA_TOO_LARGE_FOR_KEY_SIZE                110
# define KYBER_R_DATA_TOO_SMALL                             111
# define KYBER_R_DATA_TOO_SMALL_FOR_KEY_SIZE                122
# define KYBER_R_FIRST_OCTET_INVALID                        133
# define KYBER_R_INVALID_HEADER                             137
# define KYBER_R_INVALID_LABEL                              160
# define KYBER_R_INVALID_TRAILER                            139
# define KYBER_R_KEY_SIZE_TOO_SMALL                         120
# define KYBER_R_LAST_OCTET_INVALID                         134
# define KYBER_R_NULL_BEFORE_BLOCK_MISSING                  113
# define KYBER_R_SLEN_CHECK_FAILED                          136
# define KYBER_R_SLEN_RECOVERY_FAILED                       135
# define KYBER_R_UNKNOWN_ALGORITHM_TYPE                     117
# define KYBER_R_UNSUPPORTED_ENCRYPTION_TYPE                162
# define KYBER_R_UNSUPPORTED_LABEL_SOURCE                   163
# define KYBER_R_VALUE_MISSING                              147
# define KYBER_R_MISSING_PRIVATE_KEY                        148
# define KYBER_R_MISSING_PUBLIC_KEY                         149

#endif
